# To execute this pipeline, from repo root shell something like:
# pypyr default
steps:
  - name: pypyr.steps.contextsetf
    description: relatively arbitrarily setting some nested context values here
    in:
      contextSetf:
        k1:
          k1.1: v1.1
          k1.2:
            k1.2.1: v1.2.1
          k1.3: v1.3
        k2:
          k2.1: v2.1

  - name: pypyr.steps.default
    description: set context default values if they don't exist already
    in:
      defaults:
        k1:
          k1.1: this won't do anything, because it exists already
          k1.2:
            k1.2.2: '{k2[k2.1]}'
          k1.4: [0,1,2]
        k4: entirely new value
  - name: pypyr.steps.py
    description: pretty print context to stdout. notice only the new values (k1.2.2 and k1.4) were added and nothing else changed.
    in:
      py: import json; print(json.dumps(k1, indent=4))
  - name: pypyr.steps.echo
    description: and check out k4 was added
    in:
      echoMe: 'the new value in k4 is: {k4}'
